import io
import tokenize

grammar = {
  '__debug__': '__fehlerfindung__',
  '__doc__': '__dok__',
  '__import__': '__import__',
  '__name__': '__name__',
  'abs': 'bauchmuskeln',
  'and': 'und',
  'apply': 'verwende',
  'ArithmeticError': 'ArithmetischerFehler',
  'as': 'als',
  'assert': 'behaupte',
  'AssertionError': 'AnnahmeFehler',
  'AttributeError': 'AttributFehler',
  'basestring': 'basiszeichenkette',
  'bool': 'wahrfalsch',
  'break': 'abbrechen',
  'buffer': 'puffer',
  'callable': 'aufrufbar',
  'chr': 'chr',
  'class': 'klasse',
  'classmethod': 'klassenmethode',
  'cmp': 'vgl',
  'coerce': 'zwingen',
  'compile': 'kompiliere',
  'complex': 'komplex',
  'continue': 'weiter',
  'copyright': 'urheberrecht',
  'credits': 'würdigung',
  'def': 'definiere',
  'del': 'entferne',
  'delattr': 'entfattr',
  'DeprecationWarning': 'VeraltetWarnung',
  'dict': 'lexikon',
  'dir': 'verz',
  'divmod': 'divmod',
  'elif': 'wennsonst',
  'Ellipsis': 'Ellipse',
  'else': 'sonst',
  'enumerate': 'aufzählung',
  'EnvironmentError': 'UmgebungsFehler',
  'EOFError': 'EOFFehler',
  'eval': 'eval',
  'except': 'außer',
  'Exception': 'Ausnahme',
  'exec': 'erledige',
  'execfile': 'ausführedatei',
  'exit': 'raus',
  'False': 'Falsch',
  'file': 'datei',
  'filter': 'filter',
  'finally': 'schließlich',
  'float': 'fließkomma',
  'FloatingPointError': 'FließkommaFehler',
  'for': 'für',
  'from': 'von',
  'frozenset': 'gefroreneset',
  'FutureWarning': 'ZukunftsWarnung',
  'getattr': 'nimmattr',
  'global': 'global',
  'globals': 'globale',
  'hasattr': 'hatattr',
  'hash': 'hash',
  'help': 'hilfe',
  'hex': 'hex',
  'id': 'id',
  'if': 'wenn',
  'import': 'importiere',
  'ImportError': 'ImportFehler',
  'in': 'im',
  'IndentationError': 'EinruckungsFehler',
  'IndexError': 'IndexFehler',
  'input': 'eingabe',
  'int': 'ganzzahl',
  'intern': 'intern',
  'IOError': 'EAFehler',
  'is': 'ist',
  'isinstance': 'istinstanz',
  'issubclass': 'istunterklasse',
  'iter': 'iter',
  'KeyboardInterrupt': 'TastaturUnterbrechung',
  'KeyError': 'SchlüsselFehler',
  'len': 'länge',
  'license': 'lizenz',
  'list': 'liste',
  'locals': 'lokal',
  'long': 'lang',
  'LookupError': 'NachsehenFehler',
  'map': 'map',
  'max': 'max',
  'MemoryError': 'SpeicherFehler',
  'min': 'min',
  'NameError': 'NamensFehler',
  'None': 'Nichts',
  'nonlocal': 'nichtlokal',
  'not': 'nicht',
  'NotImplemented': 'NichtImplementiert',
  'NotImplementedError': 'NichtImplementiertFehler',
  'object': 'objekt',
  'oct': 'oct',
  'open': 'öffne',
  'or': 'oder',
  'ord': 'ord',
  'OSError': 'BetriebssystemFehler',
  'OverflowError': 'ÜberGrenzeFehler',
  'OverflowWarning': 'ÜberGrenzeWarnung',
  'pass': 'pass',
  'PendingDeprecationWarning': 'AusstehendeEinstellungWarnung',
  'pow': 'hoch',
  'print': 'drucken',
  'property': 'eigenschaft',
  'quit': 'schließe',
  'raise': 'behandle',
  'range': 'bereich',
  'raw_input': 'raw_input',
  'reduce': 'reduziere',
  'ReferenceError': 'ReferenzFehler',
  'reload': 'ladeneu',
  'repr': 'repr',
  'return': 'zurück',
  'reversed': 'umgekehrt',
  'round': 'runde',
  'RuntimeError': 'LaufzeitFehler',
  'RuntimeWarning': 'LaufzeitWarnung',
  'self': 'selbst',
  'set': 'menge',
  'setattr': 'setzeattr',
  'slice': 'schlitz',
  'sorted': 'sortiert',
  'sqrt': 'quadratwurzel',
  'StandardError': 'StandardFehler',
  'staticmethod': 'statischemethode',
  'StopIteration': 'StopIteration',
  'str': 'zeichenkette',
  'sum': 'summe',
  'super': 'ober',
  'SyntaxError': 'SyntaxFehler',
  'SyntaxWarning': 'SyntaxWarnung',
  'SystemError': 'SystemFehler',
  'SystemExit': 'SystemAusgang',
  'TabError': 'TabFehler',
  'True': 'Wahr',
  'try': 'versuche',
  'tuple': 'tupel',
  'type': 'typ',
  'TypeError': 'TypFehler',
  'UnboundLocalError': 'UngebundenLokalFehler',
  'unichr': 'unichr',
  'unicode': 'unicode',
  'UnicodeDecodeError': 'UnicodeDecodierungsFehler',
  'UnicodeEncodeError': 'UnicodeCodierungsFehler',
  'UnicodeError': 'UnicodeFehler',
  'UnicodeTranslateError': 'UnicodeÜrbersetzungsFehler',
  'UserWarning': 'BenutzerWarnung',
  'ValueError': 'WertFehler',
  'vars': 'variablen',
  'Warning': 'Warnung',
  'while': 'solange',
  'WindowsError': 'FensterFehler',
  'with': 'mit',
  'xrange': 'xbereich',
  'yield': 'ergibt',
  'ZeroDivisionError': 'NullTeilungsFehler',
  'zip': 'zip',
}
grammar_reverse = {value: key for key, value in grammar.items()}


def swap(input_string, dict):
  src = io.BytesIO(input_string.encode())
  tokens = []
  prev_end = (0, 0)
  for token in tokenize.tokenize(src.readline):
    if token.type == tokenize.NAME and token.string in dict:
      # Check for spaces before the token
      spaces = token.start[1] - prev_end[1]
      if token.start[0] > prev_end[0]:
        spaces = token.start[1]
      tokens.append(' ' * spaces)
      tokens.append(dict[token.string])
    elif token.type == tokenize.NEWLINE:
      tokens.append(token.string)
    elif token.type not in (tokenize.ENCODING, tokenize.ENDMARKER):
      # Check for spaces before the token
      spaces = token.start[1] - prev_end[1]
      if token.start[0] > prev_end[0]:
        spaces = token.start[1]
      tokens.append(' ' * spaces)
      tokens.append(token.string)
    prev_end = token.end

  return ''.join(tokens)
