grammar = {
  'and': 'und',
  'assert': 'behaupte',
  'break': 'abbrechen',
  'class': 'klasse',
  'continue': 'weiter',
  'def': 'definiere',
  'del': 'entferne',
  'elif': 'wennsonst',
  'else': 'sonst',
  'except': 'ausser',
  'exec': 'erledige',
  'finally': 'schliesslich',
  'for': 'fuer',
  'from': 'von',
  'if': 'wenn',
  'import': 'importiere',
  'in': 'im',
  'not': 'nicht',
  'or': 'oder',
  'pass': 'pass',
  'print': 'drucken',
  'raise': 'behandle',
  'return': 'zurueck',
  'try': 'versuche',
  'while': 'solange',
  'yield': 'ergibt',
}
